# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - whitefly-flask-asgi

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_bb07e5f0de8f43c28d88d85c77947782 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_f5eb3e4b7f2c45e5bac95f59b72cbe25 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bb07e5f0de8f43c28d88d85c77947782 }}/whitefly-flask-asgi:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'whitefly-flask-asgi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_a71c75bd93b643a2a10921cbf5e17a16 }}
        images: 'ghcr.io/${{ secrets.AzureAppService_ContainerUsername_bb07e5f0de8f43c28d88d85c77947782 }}/whitefly-flask-asgi:${{ github.sha }}'